import * as FileSystem from "expo-file-system/legacy";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Platform } from "react-native";

import { getCollegeLogoDataUri } from "@/lib/college-logo";

export type ExportAttendanceRow = {
  student: string;
  enrollmentNumber: string;
  status: "Present" | "Absent" | "Manual";
  method: string;
};

export type AttendanceReport = {
  date: string;
  subject: string;
  classDivision: string;
  rows: ExportAttendanceRow[];
};

function escapeHtml(value: string) {
  return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);
}

function csvCell(value: string) {
  return `"${value.replace(/"/g, '""')}"`;
}

export function createAttendanceCsv(report: AttendanceReport) {
  const heading = ["Student", "Enrollment number", "Status", "Attendance method"].join(",");
  const rows = report.rows.map((row) => [row.student, row.enrollmentNumber, row.status, row.method].map(csvCell).join(","));
  return [
    `StudyMatrix Attendance — ${report.subject}`,
    `Date: ${report.date}`,
    `Class: ${report.classDivision}`,
    "",
    heading,
    ...rows,
  ].join("\n");
}

function createAttendanceHtml(report: AttendanceReport, collegeLogoDataUri: string) {
  const present = report.rows.filter((row) => row.status === "Present" || row.status === "Manual").length;
  const percentage = report.rows.length === 0 ? 0 : Math.round((present / report.rows.length) * 100);
  const body = report.rows.map((row) => `<tr><td>${escapeHtml(row.student)}</td><td>${escapeHtml(row.enrollmentNumber)}</td><td class="${row.status === "Absent" ? "absent" : "present"}">${escapeHtml(row.status)}</td><td>${escapeHtml(row.method)}</td></tr>`).join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/><style>@page{margin:24px}body{font-family:Arial,sans-serif;color:#172033}.report-header{display:flex;align-items:center;gap:14px;padding-bottom:14px;border-bottom:2px solid #C89B3C}.college-logo{width:64px;height:64px;object-fit:contain}.heading-copy{flex:1}h1{color:#0B1F3A;margin:0;font-size:24px}.eyebrow{color:#6B1E2F;font-weight:700;letter-spacing:1px;font-size:10px;margin-top:4px}.meta{margin:20px 0;padding:14px;background:#F8F6F1;border-left:4px solid #C89B3C}.metric{font-size:28px;color:#0B1F3A;font-weight:700;margin-top:3px}table{width:100%;border-collapse:collapse;margin-top:18px;font-size:11px}th{background:#0B1F3A;color:#fff;text-align:left;padding:9px}td{border-bottom:1px solid #E6E0D7;padding:9px}.present{color:#237A57;font-weight:700}.absent{color:#B42318;font-weight:700}.footer{margin-top:24px;color:#667085;font-size:10px}</style></head><body><header class="report-header"><img class="college-logo" src="${collegeLogoDataUri}" alt="ICRE college crest"/><div class="heading-copy"><h1>StudyMatrix Attendance</h1><div class="eyebrow">INSTITUTE OF CIVIL AND RURAL ENGINEERING · COMPUTER DEPARTMENT</div></div></header><div class="meta"><strong>${escapeHtml(report.subject)}</strong><br/>${escapeHtml(report.classDivision)} · ${escapeHtml(report.date)}<div class="metric">${percentage}% present</div></div><table><thead><tr><th>Student</th><th>Enrollment no.</th><th>Status</th><th>Method</th></tr></thead><tbody>${body}</tbody></table><div class="footer">Generated by StudyMatrix Attendance · Developed by Vinayraj Kore</div></body></html>`;
}

async function shareFile(uri: string, mimeType: string, dialogTitle: string) {
  if (!(await Sharing.isAvailableAsync())) throw new Error("File sharing is not available on this device");
  await Sharing.shareAsync(uri, { mimeType, dialogTitle });
}

export async function shareAttendancePdf(report: AttendanceReport) {
  if (Platform.OS === "web") throw new Error("PDF export is available in the Android application");
  const collegeLogoDataUri = await getCollegeLogoDataUri();
  const { uri } = await Print.printToFileAsync({ html: createAttendanceHtml(report, collegeLogoDataUri) });
  await shareFile(uri, "application/pdf", "Share attendance PDF");
}

export async function shareAttendanceCsv(report: AttendanceReport) {
  if (Platform.OS === "web") throw new Error("CSV export is available in the Android application");
  const directory = FileSystem.cacheDirectory ?? FileSystem.documentDirectory;
  if (!directory) throw new Error("The app cache directory is unavailable");
  const fileUri = `${directory}studymatrix-attendance-${Date.now()}.csv`;
  await FileSystem.writeAsStringAsync(fileUri, createAttendanceCsv(report), { encoding: FileSystem.EncodingType.UTF8 });
  await shareFile(fileUri, "text/csv", "Share attendance CSV");
}
