import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Platform } from "react-native";

import { getCollegeLogoDataUri } from "@/lib/college-logo";

export type DailyAttendanceLecture = {
  subject: string;
  teacherName: string;
  classDivision: string;
  room: string;
  timeSlot: string;
  absentStudents: Array<{ name: string; enrollmentNumber: string }>;
};

export type DailyAttendanceReport = {
  date: string;
  lectures: DailyAttendanceLecture[];
};

function escapeHtml(value: string) {
  return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);
}

function createDailyAttendanceHtml(report: DailyAttendanceReport, collegeLogoDataUri: string) {
  const totalAbsences = report.lectures.reduce((total, lecture) => total + lecture.absentStudents.length, 0);
  const lectureSections = report.lectures.map((lecture) => {
    const absences = lecture.absentStudents.length === 0
      ? '<tr><td colspan="2" class="present">No absences recorded</td></tr>'
      : lecture.absentStudents.map((student) => `<tr><td>${escapeHtml(student.name)}</td><td>${escapeHtml(student.enrollmentNumber)}</td></tr>`).join("");
    return `<section><div class="lecture"><strong>${escapeHtml(lecture.subject)}</strong><span>${escapeHtml(lecture.timeSlot)} · ${escapeHtml(lecture.room)}</span><small>${escapeHtml(lecture.teacherName)} · ${escapeHtml(lecture.classDivision)}</small></div><table><thead><tr><th>Absent student</th><th>Enrollment no.</th></tr></thead><tbody>${absences}</tbody></table></section>`;
  }).join("");

  return `<!DOCTYPE html><html><head><meta charset="utf-8"/><style>@page{margin:24px}body{font-family:Arial,sans-serif;color:#172033}.report-header{display:flex;align-items:center;gap:14px;padding-bottom:14px;border-bottom:2px solid #C89B3C}.college-logo{width:64px;height:64px;object-fit:contain}.heading-copy{flex:1}h1{color:#0B1F3A;margin:0;font-size:24px}.eyebrow{color:#6B1E2F;font-weight:700;letter-spacing:1px;font-size:10px;margin-top:4px}.meta{margin:20px 0;padding:14px;background:#F8F6F1;border-left:4px solid #C89B3C}.metric{font-size:28px;color:#0B1F3A;font-weight:700;margin-top:3px}section{margin-top:19px}.lecture{background:#0B1F3A;color:#fff;padding:11px 12px;border-radius:8px 8px 0 0}.lecture strong,.lecture span,.lecture small{display:block}.lecture span{font-size:11px;color:#E9D9A8;margin-top:3px}.lecture small{font-size:10px;color:#D1DBE8;margin-top:4px}table{width:100%;border-collapse:collapse;font-size:11px}th{background:#EEF2F6;color:#0B1F3A;text-align:left;padding:8px}td{border-bottom:1px solid #E6E0D7;padding:8px}.present{color:#237A57;font-weight:700}.footer{margin-top:24px;color:#667085;font-size:10px}</style></head><body><header class="report-header"><img class="college-logo" src="${collegeLogoDataUri}" alt="ICRE college crest"/><div class="heading-copy"><h1>StudyMatrix Daily Attendance Report</h1><div class="eyebrow">INSTITUTE OF CIVIL AND RURAL ENGINEERING · COMPUTER DEPARTMENT</div></div></header><div class="meta"><strong>${escapeHtml(report.date)}</strong><div class="metric">${totalAbsences} absence${totalAbsences === 1 ? "" : "s"} across ${report.lectures.length} lecture${report.lectures.length === 1 ? "" : "s"}</div></div>${lectureSections}<div class="footer">Absences are grouped by subject lecture. Generated by StudyMatrix Attendance · Developed by Vinayraj Kore</div></body></html>`;
}

export async function shareDailyAttendancePdf(report: DailyAttendanceReport) {
  if (Platform.OS === "web") throw new Error("Daily PDF export is available in the Android application");
  const collegeLogoDataUri = await getCollegeLogoDataUri();
  const { uri } = await Print.printToFileAsync({ html: createDailyAttendanceHtml(report, collegeLogoDataUri) });
  if (!(await Sharing.isAvailableAsync())) throw new Error("File sharing is not available on this device");
  await Sharing.shareAsync(uri, { mimeType: "application/pdf", dialogTitle: "Share full-day attendance report" });
}
